### PR TITLE
Add initial data in ome.zarr format

### PR DESCRIPTION
**Pull request by constantinpape**
@joshmoore @tischi 
I have added the data in the format we have discussed now and also uploaded it to the embl s3 (it's 11.3 GB in total).

I added one more thing to the metadata for the multiscale datasets:
there is a field `scales` that contains a list of the absolute downscaling factors for the individual zarr arrays in the multi-scale pyramid. I think there is no canonical way to specify it in the ome.zarr multi-scale format yet, but we will definitely need it for bdv.

### CODE REVIEW

**Comment by tischi** [comment]
> I think there is no canonical way to specify it in the ome.zarr multi-scale format yet, but we will definitely need it for bdv.

Does that mean I have to wait for this to be fixed before I can start trying things out?

**Comment by constantinpape** [comment]
> Does that mean I have to wait for this to be fixed before I can start trying things out?

No, you can just read the `scales` field from the multiscale metadata and pass it to bdv.

**Comment by joshmoore** [comment]
```
$ ome_zarr info https://s3.embl.de/i2k-2020/em-raw.ome.zarr/setup0/timepoint0
https://s3.embl.de/i2k-2020/em-raw.ome.zarr/setup0/timepoint0/ [zgroup]
 - metadata
   - Multiscales
 - data
   - (1, 1, 2854, 3240, 3438)
   - (1, 1, 1427, 1620, 1719)
   - (1, 1, 714, 810, 860)
   - (1, 1, 357, 405, 430)
   - (1, 1, 179, 203, 215)
   - (1, 1, 90, 102, 108)
   - (1, 1, 45, 51, 54)
```

https://hms-dbmi.github.io/vizarr?source=https%3A%2F%2Fs3.embl.de%2Fi2k-2020%2Fem-raw.ome.zarr%2Fsetup0%2Ftimepoint0 also resolves. Having issues with napari that I'll look into.

cc: @will-moore

**Comment by constantinpape** [comment]
@joshmoore just checking:
the snippet you posted means that you can correctly parse the data, right?

**Comment by joshmoore** [comment]
Yes, and the Javascript library can read it. :+1:

**Pull request merged**
